### PR TITLE
add :elpaca keyword

### PR DESCRIPTION
**Pull request by yk-kd**
Add :elpaca keyword
This keyword mentioned at #155 .

### CODE REVIEW

**Comment by yk-kd** [comment]
Hello @conao3 
Fixed, please approve the workflow.

**Comment by conao3** [comment]
Oops, approved.

**Comment by conao3** [comment]
And I have to update workflow definition; Emacs-26 is too old :(

**Comment by conao3** [comment]
Awesome, congrats first contribution for leaf-keywords :tada:

**Comment by dpassen** [comment]
Mind sharing an example init.el with elpaca and leaf?

**Comment by yk-kd** [comment]
@dpassen e.g.
```el
(defvar elpaca-installer-version 0.8)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca leaf (require 'leaf))
(elpaca leaf-keywords
  (require 'leaf-keywords)
  ;; use :ensure keyword instead of :elpaca
  ;; (custom-set-variables '(leaf-alias-keyword-alist '((:ensure . :elpaca))))
  (leaf-keywords-init))
(elpaca-wait)
;; You can use it as you like from here.
(leaf hydra :elpaca t)

```

**Comment by dpassen** [comment]
Thank you so much!

**Pull request merged**
